### ISSUE TITLE
GridFieldOrderableRows does not support secondary or default sort fields.

### ISSUE THREAD

**Issue by davejtoews** [symbiote/silverstripe-gridfieldextensions#324] opened 2021-08-24 16:40 UTC
I frequently have orderable objects which should have a default sort order, but option for manually overriding. So the object will have something like:

```php
private static $default_sort = 'Sort ASC, Title ASC`;
```

With the `GridFieldOrderableRows` component added, only the sort column managed by the component itself is considered in the CMS display of the items. If no values have been set in the sort field they display unsorted in whichever order SQL decides to show them. (Mostly just ordered by id).

The component offers a getter and setter for `$extraSortFields` but these are applied as higher priority sorts than the managed sort column. What I'm looking for is setting sorts with a lower priority than the managed sort column, preferably making use of the defaults set elsewhere.

PRs
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/325
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/329
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/349

**Comment by GuySartorelli** [comment] 2023-03-19 21:58
Closing as a duplicate of https://github.com/symbiote/silverstripe-gridfieldextensions/issues/357 (we took the latter through backlog refinement today)

**Closed as completed by GuySartorelli** 2023-03-19 21:58 UTC
Labels: type/enhancement, affects/v4, impact/medium
