### ISSUE TITLE
Invalid form field instance for column "ID" 

### ISSUE THREAD

**Issue by tiefseh** [symbiote/silverstripe-gridfieldextensions#280] opened 2019-01-09 13:37 UTC
I get that error when adding the GridFieldEditableColumns-component. 

Silverstripe 4.2
I' m using an extended DataObject

**Comment by robbieaverill** [comment] 2019-01-09 15:21
Hi @tiefseh, can you please provide the part of your code that adds the component?

**Comment by tiefseh** [comment] 2019-01-10 18:53
Hej @robbieaverill 
that s the code,... 
```
$housingUnits = new GridField(
	'HousingUnits',
	'Wohneinheiten im Überblick',
	$this->HousingUnits(),
	GridFieldConfig_RelationEditor::create()
	->addComponent(new GridFieldEditableColumns())
);
```
I tried the example code from here too, but the same error appears

**Comment by robbieaverill** [comment] 2019-01-14 13:04
@tiefseh I can't reproduce this with SilverStripe 4.3.x-dev and the following code:

```php
use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\GridField\GridField;
use SilverStripe\Forms\GridField\GridFieldConfig_RelationEditor;
use SilverStripe\Security\Member;
use Symbiote\GridFieldExtensions\GridFieldEditableColumns;

class Page extends SiteTree
{
    private static $db = [];

    private static $has_one = [];

    private static $many_many = [
        'Members' => Member::class,
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $members = new GridField(
            'Members',
            'Wohneinheiten im Überblick',
            $this->Members(),
            GridFieldConfig_RelationEditor::create()
                ->addComponent(new GridFieldEditableColumns())
        );

        $fields->addFieldToTab('Root.Main', $members);

        return $fields;
    }
}
```

The GridField loads correctly for me. 

I'm going to close this for now, but please feel free to reopen it with a clear example of how to reproduce your issue =)

**Closed by robbieaverill** 2019-01-14 13:04 UTC
