### ISSUE TITLE
ss4.0.1 live table sort field is not updated using ordarablerows

### ISSUE THREAD

**Issue by guyvanbael** [symbiote/silverstripe-gridfieldextensions#237] opened 2018-01-18 14:45 UTC
addding ordarable rows is working as long as you are logged in (draft). When logged out. The sortorder is different. I checked the table and the sort field isn't getting updated when the dataobject is published.

The dataobject is published automatically (owns) when the parentpage is published.
`		// PRODUCTEN
        $itemsInGrid = $this->Producten()->sort('Sort');  // get a list of object you want to show
        $config = GridFieldConfig_RecordEditor::create(); 
        $config->addComponent(new GridFieldOrderableRows('Sort'));
        $config->getComponentByType('SilverStripe\Forms\GridField\GridFieldDataColumns')
        ->setDisplayFields([
            'Productnaam' => 'Naam',
        ]);

        $gridField = new GridField("Producten", "Producten", $itemsInGrid, $config);
        $fields->addFieldToTab('Root.guy', $gridField);`

**Comment by mlewis-everley** [comment] 2018-01-19 11:28
I think this is a duplicate of issue #38 

We are hitting the same issue in SS4, but the suggested module seems to work.

**Closed** 2018-01-23 00:56 UTC
